// <auto-generated />
using System;
using GerenciamentoCliente.Adm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciamentoCliente.Adm.Migrations
{
    [DbContext(typeof(GerenciamentoClienteContexto))]
    partial class GerenciamentoClienteContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estadoid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cidades");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_cidades_estadoid");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_cidades_nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nome"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nome"), new[] { "gin_trgm_ops" });

                    b.ToTable("cidades", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("Nascimento")
                        .HasColumnType("date")
                        .HasColumnName("nascimento");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomecompleto");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cpf")
                        .HasDatabaseName("ix_clientes_cpf");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Cpf"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Cpf"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_clientes_email");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Email"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Email"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NomeCompleto")
                        .HasDatabaseName("ix_clientes_nomecompleto");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NomeCompleto"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NomeCompleto"), new[] { "gin_trgm_ops" });

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("cidadeid");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("pk_enderecos");

                    b.HasIndex("Bairro")
                        .HasDatabaseName("ix_enderecos_bairro");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Bairro"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Bairro"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_enderecos_cidadeid");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_enderecos_clienteid");

                    b.HasIndex("Logradouro")
                        .HasDatabaseName("ix_enderecos_logradouro");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Logradouro"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Logradouro"), new[] { "gin_trgm_ops" });

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Cidade", b =>
                {
                    b.HasOne("GerenciamentoCliente.Adm.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cidades_estados_estadoid");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Endereco", b =>
                {
                    b.HasOne("GerenciamentoCliente.Adm.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enderecos_cidades_cidadeid");

                    b.HasOne("GerenciamentoCliente.Adm.Models.Cliente", "Cliente")
                        .WithMany("Enderecos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enderecos_clientes_clienteid");

                    b.Navigation("Cidade");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Cliente", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("GerenciamentoCliente.Adm.Models.Estado", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
